apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: manage-paas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: 192.168.0.175:8091/jenkins-project/springboot-demo:latest   # 会被动态替换
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
  namespace: manage-paas
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: NodePort   # 如果是本地 kind 集群，使用 NodePort 方便访问